#


qac:
	pdflatex memo_qac.tex


# M100:        https://www.overleaf.com/project/5d55486d26900c000189ce35    git clone https://git.overleaf.com/5d55486d26900c000189ce35
# N346:        https://www.overleaf.com/5263516468jywmsrvcyddn              git clone https://git.overleaf.com/5d52bbb6f8724362e46b0e07
# skymodel:    https://www.overleaf.com/6799949182tqhbtvcxbwdd              git clone https://git.overleaf.com/5d557ff05a59b7784800c1bb
# GaussSim     https://www.overleaf.com/3355477475zffqdkpnjpjp              git clone https://git.overleaf.com/5d55330c1d7b3e0001c38c10
# outflow:     
# HI:          https://www.overleaf.com/read/dnstbdwtxpjk                   ???

m100:
	git clone https://git.overleaf.com/5d55486d26900c000189ce35 m100

skymodel:
	git clone https://git.overleaf.com/5d557ff05a59b7784800c1bb skymodel

gausssim:
	git clone https://git.overleaf.com/5d55330c1d7b3e0001c38c10 gausssim

outflow:
	@echo TBD

n346:
	git clone https://git.overleaf.com/5d52bbb6f8724362e46b0e07 n346

HI:
	@echo TBD
