# Do not edit this file, it has been generated via configure in scripts4paper
#
# define setup parameters for our "scripts4paper" scripts and data
# also figure out if we're in python2 (CASA5) or python3 (CASA6)

_s4p      = '/vol/arc3/data1/arc2_data/moser/DataComb/DCSlack/dc2019/scripts4paper/'        # the S4P scripts directory

_s4p_data = '/vol/arc3/data1/arc2_data/moser/DataComb/DCSlack/data'   # the S4P data directory, read only from here?
_s4p_work = '/vol/arc3/data1/arc2_data/moser/DataComb/DCSlack/DC_Ly_tests'   # the S4P work directory, write here?


#pathtoastropy = '/users/moser/.local/lib/python3.6/site-packages'
#sys.path.append(pathtoastropy)               # path to the folder with datacomb.py and ssc_DC.py



#  Lydia's original names
pathtoconcat = '/vol/arc3/data1/arc2_data/moser/DataComb/DCSlack/ToshiSim/skymodel-c.sim/skymodel-c_120L/'   # path to the folder with the files to be concatenated
pathtoimage  = '/vol/arc3/data1/arc2_data/moser/DataComb/DCSlack/DC_Ly_tests/'                          # path to the folder where to put the combination and image results

# reuse them, but we should move to use the S4P variables
pathtoconcat = _s4p_data     # e.g. _s4p_data/skymodel-c.sim/skymodel-c_120L  is the root directory
pathtoimage  = _s4p_work


# why do we need two here ?
datacombpath = _s4p
TP2VISpath   = _s4p

import sys
sys.path.append(_s4p)


#  helper function for DC_script.py
def function_exists(fn):
    """
         fn (string) :  name of the function (or variable) to test if it exists
                        in your current python environment
    """
    #   surely there must be a better pythonic way for this?
    #   but this does work :-)
    try:
        a=eval('dir(%s)' % fn)
        print("Hurrah, %s exists" % fn)
        return True
    except:
        print("Warning: function %s not known" % fn)
        return False
    # should never get here
    return None


#  we can't work without the new sdintimaging....
if not function_exists('sdintimaging'):
    print('#########################################################')
    print('Your CASA version does not seem to  support sdintimaging.')
    print('Please use at least 6.1.x')
    print('Aborting script ...')
    print('#########################################################')
    sys.exit(1)


print("Setup of /vol/arc3/data1/arc2_data/moser/DataComb/DCSlack/dc2019/scripts4paper complete for python3 only")
print("S4P_DATA = /vol/arc3/data1/arc2_data/moser/DataComb/DCSlack/data")
print("S4P_WORK = /vol/arc3/data1/arc2_data/moser/DataComb/DCSlack/DC_Ly_tests")
